version: 2

jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:  
                name: Inject build date
                command: ./scripts/inject-build-date.sh
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # Test the source code
            - run:
                name: Testing
                command: npm run test -- --watch=false
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: npm run build -- --prod --base-href "https://torbjorv.github.io/shadebobs/"
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist


    deploy_dev:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        steps:
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore cache from the build job which contains the
            # dist folder that needs to be deployed
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Deploy Dev
                command: ./scripts/deploy-to-branch.sh $GH_TOKEN deploy-dev
    
    # deploy_stable:
    #     working_directory: ~/project
    #     docker:
    #         - image: circleci/node:11.15-browsers
    #     steps:
    #         - checkout
    #         # Log the current branch
    #         - run:
    #             name: Show current branch
    #             command: echo ${CIRCLE_BRANCH}
    #         # Restore cache from the build job which contains the
    #         # dist folder that needs to be deployed
    #         - restore_cache:
    #             key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
    #         - run:
    #             name: Deploy Stable
    #             command: ./scripts/deploy-to-branch.sh $GH_TOKEN gh-pages


workflows:
    version: 2
    build_and_deploy_dev:
        jobs:
            - build
            - deploy_dev:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
    # build_and_deploy_stable:
    #     jobs:
    #         - build
    #         - approve:
    #             type: approval
    #             requires:
    #                 - build
    #         - deploy_stable:
    #             requires:
    #                 - approve
    #             filters:
    #                 branches:
    #                     only:
    #                         - master